server:
  port: 0

eureka:
  client:
    service-url:
      default-zone: http://eureka:password@localhost:8761/eureka

spring:
  application:
    name: product-service

  data:
    mongodb:
      uri: mongodb://localhost:27017/hoaxify_product
